language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install protractor -g
    - npm i -g npm@latest

install:
  - npm i

script:
  - npm run lint:ci
  - npm run build:ci
  - npm run test

git:
  depth: 1
